# -*- coding: utf-8 -*-
"""IntroductionML.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YUsXUDvHmO16VXkTWe5aEOVhp6as3MfA

***Introduction to Machine Learning***

Making a computer learn by analyzing data and statistics is known as **machine learning. **

A **data set** is any collection of data in a computer's mind. It might be anything, including an array or a whole database.

Data is a collection of samples with d features.

Feature is an elementary descriptor of an entity.

A sample is an entity encoding an object, usually encoded as a vector `R^d`

Let us consider a dataset composed N samples and each sample being encoded by d features:

Data: `X∈R^n*d`
Sample: `x∈R^d`

***Mean, median and mode***

As we know from statistics:

Mean is the average value
Median is the mid point value
Mode is the most common value

Let us suppose we have a list of speed of 13 cars like below:

`speed = [99,86,87,88,111,86,103,87,94,78,77,85,86]`

Let us calculate mean, median and mode for this list using numpy and scipy libraries:
"""

import numpy as np
from scipy import stats

speed = [99,86,87,88,111,86,103,87,94,78,77,85,86]

print("Mean: ", np.mean(speed))

print("Median: ", np.median(speed))

print("Mode: ", stats.mode(speed))

"""Standard deviation is a number that describes how spread out the values are."""

print("Standart deviation: ", np.std(speed))

"""Variance is a measurement of the spread between numbers in a data set. 

To calculate the variance you have to do as follows:

1. Find the mean:
`(32+111+138+28+59+77+97) / 7 = 77.4`

2. For each value: find the difference from the mean:

`32 - 77.4 = -45.`

`111 - 77.4 =  33.6`

`138 - 77.4 =  60.6`

 `28 - 77.4 = -49.4`

 `59 - 77.4 = -18.4`

` 77 - 77.4 = - 0.4`

` 97 - 77.4 =  19.6`

3. For each difference: find the square value:

`(-45.4)2 = 2061.16`

` (33.6)2 = 1128.96`

` (60.6)2 = 3672.36`

`(-49.4)2 = 2440.36`

`(-18.4)2 =  338.56`

`(- 0.4)2 =    0.16`

` (19.6)2 =  384.16`

4. The variance is the average number of these squared differences:

`(2061.16+1128.96+3672.36+2440.36+338.56+0.16+384.16) / 7 = 1432.2`

Let us calculate variance for our list (speed) using numpy library's **var** function:
"""

print("Variance: ", np.var(speed))

"""Standart deviation is a square root of variance."""